### PR TITLE
Remove node10 and node6 dependencies

### PR DESCRIPTION
**Pull request by rick-s-wicker**
No issues on my side, I've been running for a couple months.

### CODE REVIEW

**Comment by krzysztof-madej** [comment]
Any chances to merge it?

**Comment by rick-s-wicker** [comment]
No response from the owner

**Comment by colindembovsky** [comment]
Merged this in - needed to update tests and other versions etc. so it took some time.

**Comment by rick-s-wicker** [comment]
Thank you! I will check over what you did and do a better job next time.

Thanks,
Rick

**Pull request merged**
